SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE telecloud;

CREATE TABLE eventistr (
	id BIGINT NOT NULL AUTO_INCREMENT,
	gdoevento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	tipotlc VARCHAR(50) NOT NULL,
	datotlc INTEGER NULL,
	addrperif INTEGER NULL,
	versione INTEGER NOT NULL,
	formato INTEGER NOT NULL,
	processo VARCHAR(50) NOT NULL,
	tipoprocesso VARCHAR(50) NOT NULL,
	tipoinfo VARCHAR(50) NOT NULL,
	numeromsgappl INTEGER NOT NULL,
	tipoevento VARCHAR(50) NOT NULL,
	transazione VARCHAR(50) NULL,
	tiporivelatore VARCHAR(50) NULL,
	areaapplicativa VARCHAR(50) NULL,
	provenienza VARCHAR(50) NULL,
	categoria VARCHAR(50) NULL,
	classeelemento VARCHAR(50) NULL,
	numeroelemento INTEGER NULL,
	idcommento INTEGER NULL,
	commento VARCHAR(250) NULL,
	idimpianto INTEGER NULL,
	nomeimpianto VARCHAR(50) NULL,
	ipaddr VARCHAR(50) NULL,
	CONSTRAINT eventistr_pk PRIMARY KEY ( id )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
