SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE telecloud;

CREATE TABLE pgmissues (
	id BIGINT NOT NULL AUTO_INCREMENT,
	programmazione MEDIUMTEXT NOT NULL,
	nomeutente VARCHAR(255) NOT NULL,
	nomesito VARCHAR(255) NULL,
	nomedevice VARCHAR(255) NOT NULL,
	idutente BIGINT NOT NULL,
	idsito BIGINT NOT NULL,
	iddevice BIGINT NOT NULL,
	issuetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	errore INTEGER NOT NULL,
	commento VARCHAR(255) NOT NULL,
	CONSTRAINT pgmissues_pk PRIMARY KEY ( id )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
