SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE telecloud;

CREATE TABLE energy (
	id BIGINT NOT NULL AUTO_INCREMENT,
	device_id BIGINT NOT NULL,
	gdo DATE NOT NULL,
	energydata VARCHAR(2048) NOT NULL,
	CONSTRAINT energy_pk PRIMARY KEY ( id )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE energy ADD CONSTRAINT energy_fk_device FOREIGN KEY ( device_id ) REFERENCES device ( id );

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
